#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User

#fos_ck_editor:
#  input_sync: true
#  default_config: base_config
#  configs:
#    base_config:
#      toolbar:
#        - { name: "styles", items: ['Bold', 'Italic', 'BulletedList', 'Link'] }

easy_admin:
  design:
    assets:
      js:
        - '/bundles/cksourceckfinder/ckfinder/ckfinder.js'
        - '/js/setup-ckfinder.js'
        # ...
  entities:
    Utilisateurs:
      class: App\Entity\User
      form:
        fields:
          - username
          - email
          - enabled
          - lastLogin
          # if administrators are allowed to edit users' passwords and roles, add this:
          - { property: 'plainPassword', type: 'text', type_options: { required: false } }
          - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
    Articles:
      class: App\Entity\Article
      form:
        fields:
          - title
          - { property: 'content', type: 'fos_ckeditor' }
    Categories:
      class: App\Entity\Category