#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User

#fos_ck_editor:
#  input_sync: true
#  default_config: base_config
#  configs:
#    base_config:
#      toolbar:
#        - { name: "styles", items: ['Bold', 'Italic', 'BulletedList', 'Link'] }

easy_admin:
  design:
    form_theme:
      - 'form_div_layout.html.twig'
      - '@EasyAdmin/form/bootstrap_4.html.twig'
      - '@VichUploader/Form/fields.html.twig'
    assets:
      js:
        - '/bundles/cksourceckfinder/ckfinder/ckfinder.js'
        - '/js/setup-ckfinder.js'
        # ...
  entities:
    Articles:
      class: App\Entity\Article
      list:
        actions: ['show']
        fields:
          - { property: 'title', label: 'Titre' }
          - { property: 'writer', label: 'Auteur de l`article' }
          - { property: 'image', template: 'vich_uploader_image.html.twig' }
          - { property: 'isPublished', label: 'Article en publication' }
          - { property: 'content', label: 'Article' }

      show:
        fields:
          #          - { type: 'tab' , label: 'Basic Information' }
          - { property: 'title', label: 'Titre' }
          - { property: 'content', label: 'Article', type: 'fos_ckeditor' }
          - { property: 'linkedCategory', label: 'Catégorie(s)' }
          - { property: 'linkedAuthor', label: 'Auteur(s) en relation' }
          - { property: 'linkedConcept', label: 'Concept(s) en relation' }
          - { property: 'writer', label: 'Auteur de l`article' }
          - { property: 'imageFile', label: 'Illustration', type: 'vich_image' }
          - { property: 'isPublished', label: 'Article en publication' }
      form:
        fields:
#          - { type: 'tab' , label: 'Basic Information' }
          - { property: 'title', label: 'Titre' }
          - { property: 'content', label: 'Article', type: 'fos_ckeditor' }
          - { property: 'linkedCategory', label: 'Catégorie(s)' }
          - { property: 'linkedAuthor', label: 'Auteur(s) en relation' }
          - { property: 'linkedConcept', label: 'Concept(s) en relation' }
          - { property: 'writer', label: 'Auteur de l`article' }
          - { property: 'imageFile', label: 'Illustration', type: 'vich_image' }
          - { property: 'isPublished', label: 'Article en publication' }
    Categories:
      class: App\Entity\Category
      list:
        fields:
        - { property: 'name', label: 'Catégories' }
      form:
        fields:
          - { property: 'name', label: 'Catégories' }
    Concepts:
      class: App\Entity\Concept
      list:
        fields:
          - { property: 'name', label: 'Concepts' }
      form:
        fields:
          - { property: 'name', label: 'Concepts' }

    Auteurs:
      class: App\Entity\Author
      list:
        fields:
          - { property: 'firstname', label: 'Prénom' }
          - { property: 'lastname', label: 'Nom' }
          - { property: 'name', label: 'dit' }
          - { property: 'birthday', label: 'Né le' }
      form:
        fields:
          - { property: 'firstname', label: 'Prénom' }
          - { property: 'lastname', label: 'Nom' }
          - { property: 'name', label: 'dit' }
          - { property: 'birthday', label: 'Né le' }
    Utilisateurs:
      class: App\Entity\User
      list:
        fields:
          - { property: 'username', label: 'Utilisateur' }
          - { property: 'email', label: 'E-mail' }
          - { property: 'enabled', label: 'Activé ?' }
          - { property: 'lastLogin', label: 'Dernière connexion' }
      form:
        fields:
          - { property: 'username', label: 'Utilisateur' }
          - { property: 'email', label: 'E-mail' }
          - { property: 'enabled', label: 'Activé ?' }
          - { property: 'lastLogin', label: 'Dernière connexion' }
          # if administrators are allowed to edit users' passwords and roles, add this:
          - { property: 'plainPassword', type: 'text', type_options: { required: false } }
          - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }