#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User

#fos_ck_editor:
#  input_sync: true
#  default_config: base_config
#  configs:
#    base_config:
#      toolbar:
#        - { name: "styles", items: ['Bold', 'Italic', 'BulletedList', 'Link'] }

easy_admin:
  design:
    form_theme:
      - 'form_div_layout.html.twig'
      - '@EasyAdmin/form/bootstrap_4.html.twig'
    assets:
      js:
        - '/bundles/cksourceckfinder/ckfinder/ckfinder.js'
        - '/js/setup-ckfinder.js'
        # ...
  entities:
    Articles:
      class: App\Entity\Article
      list:
        actions: ['show']
        fields:
          - title
          - category
          - author
          - linkedConcept
          - { property: 'image', template: 'vich_uploader_image.html.twig' }
          - isPublished
      show:
        fields:
          - title
          - category
          - author
          - linkedConcept
          - content
          - { property: 'image', type: 'image', base_path: '%app.path.article_images%' }
          - isPublished
      form:
        fields:
#          - { type: 'tab' , label: 'Basic Information' }
          - title
          - category
          - author
          - linkedConcept
          - { property: 'content', type: 'fos_ckeditor' }
#          - { type: 'tab', label: 'Contact Information', icon: 'phone' }
          - { property: 'imageFile', type: 'vich_image' }
    Categories:
      class: App\Entity\Category
      form:
        fields:
          - name
    Concepts:
      class: App\Entity\Concept
      form:
        fields:
          - name
    Utilisateurs:
      class: App\Entity\User
      form:
        fields:
          - username
          - email
          - enabled
          - lastLogin
          # if administrators are allowed to edit users' passwords and roles, add this:
          - { property: 'plainPassword', type: 'text', type_options: { required: false } }
          - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }