#!/usr/bin/with-contenv sh

cd /var/www/symfony
exec s6-setuidgid ${SF_UID-1000}:${SF_GID-1000} /infinity.sh "./bin/console jms-job-queue:schedule --min-job-interval=60 --verbose" "/var/www/symfony/var/log/jobs-scheduler.log" "15"
